import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/Components/Footer/Footer";
import Navbar from "@/Components/Navbar/Navbar";

const inter = Inter({ subsets: ["latin"] });
// const Lalezar = Inter({ subsets: ["arabic"], weight: ["400"] });
// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <h1 className="Height">Helloo everybody </h1>
        {children}
        <Footer />
      </body>
    </html>
  );
}
